# Starter pipeline
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Microsoft Azure Sponsorship(b075a4d9-9347-41b2-b9ac-cf43ec69d79c)'
    KeyVaultName: 'K8sauto'
    SecretsFilter: '*'
    RunAsPreJob: true
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- task: TerraformInstaller@2
  inputs:
    terraformVersion: 'latest'

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
